name = "Vanilla Addons"
author = "kekko99k0o"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0585440d5f2d28bbc4a074ea220ffb9dcc631547bb8e7f7f6e0e4c83e10a54b0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
