name = "Vanilla Addons"
author = "kekko99k0o"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a92465c56c48c5749265e649d7a5ea653bf44c20439932eed278b2c1c184c60"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
