name = "Vanilla Addons"
author = "kekko99k0o"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a151fd06afb7ca7ca8142cbc4f0b0810e4733d2fb4ebacb3e637899e683995dd"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.20.4"]
